{{- if .Values.ingresses.enabled -}}
{{- if .Values.services.web.enabled -}}
{{- $ingress := .Values.ingresses.web }}
apiVersion: traefik.containo.us/v1alpha1
kind: {{ default "IngressRoute" $ingress.className }}
metadata:
  name: {{ include "envoy.serviceName" . }}-web-ingress-route
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "envoy.labels" . | nindent 4 }}
  {{- with $ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    {{- toYaml $ingress.entryPoints | nindent 4 }}
  routes:
    - match: Host(`{{ $ingress.hostname }}`)
      kind: Rule
      services:
        - name: {{ include "envoy.serviceName" . }}-web
          namespace: {{ .Release.Namespace }}
          port: {{ .Values.services.web.port }}
  {{- with $ingress.tls }}
  tls:
    {{- toYaml $ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}
---
{{ if .Values.services.grpc.enabled -}}
{{- $ingress := .Values.ingresses.grpc }}
apiVersion: traefik.containo.us/v1alpha1
kind: {{ default "IngressRouteTCP" $ingress.className }}
metadata:
  name: {{ include "envoy.serviceName" . }}-grpc-ingress-route
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "envoy.labels" . | nindent 4 }}
  {{- with $ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    {{- toYaml $ingress.entryPoints | nindent 4 }}
  routes:
    - match: HostSNI(`{{ $ingress.hostname }}`)
      services:
        - name: {{ include "envoy.serviceName" . }}-grpc
          namespace: {{ .Release.Namespace }}
          port: {{ .Values.services.grpc.port }}
  {{- with $ingress.tls }}
  tls:
    {{- toYaml $ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}