{{- if .Values.certificate.data -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "envoy.certificatesSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "envoy.labels" . | nindent 4 }}
type: Opaque
data:
    {{ include "envoy.certificateName" . }}: {{ .Values.certificate.data }}
{{- end }}